#!/bin/bash

LOGFILE="/var/log/pypi_sync.log"

(
    echo "===== SYNC STARTED AT $(date -R) ====="
    echo "> RUN bandersnatch mirror..."
    bandersnatch mirror
    echo ""
    echo "===== SYNC FINISHED AT $(date -R) ====="
) 2>&1 | tee $LOGFILE

savelog -c {{LOG_NUM}} $LOGFILE > /dev/null

